name: Deploy

on:
  workflow_run:
    workflows: ["Docker Build"]
    types:
      - completed
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Run Migrations
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/mobile-shop
          
          declare -A schema_service_map=(
            ["user"]="user-service"
            ["phone"]="phone-service"
          )

          for schema in "${!schema_service_map[@]}"; do
            service=${schema_service_map[$schema]}
            echo "Running migrations for $service using schema $schema"
            docker-compose exec -T $service sh -c "cd /app && npx prisma migrate deploy --schema=./prisma/$schema/schema.prisma" || {
              echo "Error running migrations for $schema"
              exit 1
            }
          done
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/mobile-shop
          docker-compose down
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/phone-store-api-gateway:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/phone-store-auth-service:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/phone-store-user-service:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/phone-store-phone-service:latest
          docker-compose up -d

    - name: Slack Notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,workflow
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
      