name: Docker Build


on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ api-gateway, auth-service, user-service, phone-service, order-service, payment-service, ai-service ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests for ${{ matrix.service }}
      run: npm run test:${{ matrix.service }}

  build-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ api-gateway, auth-service, user-service, phone-service, order-service, payment-service, ai-service ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push ${{ matrix.service }}
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./apps/${{ matrix.service }}/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/phone-store-${{ matrix.service }}:latest
